// Generated by gencpp from file depth_msgs/GetDepth.msg
// DO NOT EDIT!


#ifndef DEPTH_MSGS_MESSAGE_GETDEPTH_H
#define DEPTH_MSGS_MESSAGE_GETDEPTH_H

#include <ros/service_traits.h>


#include <depth_msgs/GetDepthRequest.h>
#include <depth_msgs/GetDepthResponse.h>


namespace depth_msgs
{

struct GetDepth
{

typedef GetDepthRequest Request;
typedef GetDepthResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetDepth
} // namespace depth_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::depth_msgs::GetDepth > {
  static const char* value()
  {
    return "80c391de64e31f65e6c6d950defb26e1";
  }

  static const char* value(const ::depth_msgs::GetDepth&) { return value(); }
};

template<>
struct DataType< ::depth_msgs::GetDepth > {
  static const char* value()
  {
    return "depth_msgs/GetDepth";
  }

  static const char* value(const ::depth_msgs::GetDepth&) { return value(); }
};


// service_traits::MD5Sum< ::depth_msgs::GetDepthRequest> should match
// service_traits::MD5Sum< ::depth_msgs::GetDepth >
template<>
struct MD5Sum< ::depth_msgs::GetDepthRequest>
{
  static const char* value()
  {
    return MD5Sum< ::depth_msgs::GetDepth >::value();
  }
  static const char* value(const ::depth_msgs::GetDepthRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::depth_msgs::GetDepthRequest> should match
// service_traits::DataType< ::depth_msgs::GetDepth >
template<>
struct DataType< ::depth_msgs::GetDepthRequest>
{
  static const char* value()
  {
    return DataType< ::depth_msgs::GetDepth >::value();
  }
  static const char* value(const ::depth_msgs::GetDepthRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::depth_msgs::GetDepthResponse> should match
// service_traits::MD5Sum< ::depth_msgs::GetDepth >
template<>
struct MD5Sum< ::depth_msgs::GetDepthResponse>
{
  static const char* value()
  {
    return MD5Sum< ::depth_msgs::GetDepth >::value();
  }
  static const char* value(const ::depth_msgs::GetDepthResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::depth_msgs::GetDepthResponse> should match
// service_traits::DataType< ::depth_msgs::GetDepth >
template<>
struct DataType< ::depth_msgs::GetDepthResponse>
{
  static const char* value()
  {
    return DataType< ::depth_msgs::GetDepth >::value();
  }
  static const char* value(const ::depth_msgs::GetDepthResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // DEPTH_MSGS_MESSAGE_GETDEPTH_H
