// Generated by gencpp from file depth_msgs/GetDepthResponse.msg
// DO NOT EDIT!


#ifndef DEPTH_MSGS_MESSAGE_GETDEPTHRESPONSE_H
#define DEPTH_MSGS_MESSAGE_GETDEPTHRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace depth_msgs
{
template <class ContainerAllocator>
struct GetDepthResponse_
{
  typedef GetDepthResponse_<ContainerAllocator> Type;

  GetDepthResponse_()
    : depth(0)  {
    }
  GetDepthResponse_(const ContainerAllocator& _alloc)
    : depth(0)  {
  (void)_alloc;
    }



   typedef uint32_t _depth_type;
  _depth_type depth;





  typedef boost::shared_ptr< ::depth_msgs::GetDepthResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::depth_msgs::GetDepthResponse_<ContainerAllocator> const> ConstPtr;

}; // struct GetDepthResponse_

typedef ::depth_msgs::GetDepthResponse_<std::allocator<void> > GetDepthResponse;

typedef boost::shared_ptr< ::depth_msgs::GetDepthResponse > GetDepthResponsePtr;
typedef boost::shared_ptr< ::depth_msgs::GetDepthResponse const> GetDepthResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::depth_msgs::GetDepthResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::depth_msgs::GetDepthResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::depth_msgs::GetDepthResponse_<ContainerAllocator1> & lhs, const ::depth_msgs::GetDepthResponse_<ContainerAllocator2> & rhs)
{
  return lhs.depth == rhs.depth;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::depth_msgs::GetDepthResponse_<ContainerAllocator1> & lhs, const ::depth_msgs::GetDepthResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace depth_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::depth_msgs::GetDepthResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::depth_msgs::GetDepthResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::depth_msgs::GetDepthResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::depth_msgs::GetDepthResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::depth_msgs::GetDepthResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::depth_msgs::GetDepthResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::depth_msgs::GetDepthResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "4fb87ef1559454daf6f1b01af71125ad";
  }

  static const char* value(const ::depth_msgs::GetDepthResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x4fb87ef1559454daULL;
  static const uint64_t static_value2 = 0xf6f1b01af71125adULL;
};

template<class ContainerAllocator>
struct DataType< ::depth_msgs::GetDepthResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "depth_msgs/GetDepthResponse";
  }

  static const char* value(const ::depth_msgs::GetDepthResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::depth_msgs::GetDepthResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint32 depth   #the depth in mm of the object located at the pixel\n"
"\n"
;
  }

  static const char* value(const ::depth_msgs::GetDepthResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::depth_msgs::GetDepthResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.depth);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GetDepthResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::depth_msgs::GetDepthResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::depth_msgs::GetDepthResponse_<ContainerAllocator>& v)
  {
    s << indent << "depth: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.depth);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DEPTH_MSGS_MESSAGE_GETDEPTHRESPONSE_H
