// Generated by gencpp from file mobileNet/GetDepth.msg
// DO NOT EDIT!


#ifndef MOBILENET_MESSAGE_GETDEPTH_H
#define MOBILENET_MESSAGE_GETDEPTH_H

#include <ros/service_traits.h>


#include <mobileNet/GetDepthRequest.h>
#include <mobileNet/GetDepthResponse.h>


namespace mobileNet
{

struct GetDepth
{

typedef GetDepthRequest Request;
typedef GetDepthResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetDepth
} // namespace mobileNet


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::mobileNet::GetDepth > {
  static const char* value()
  {
    return "3e58674313cc0990de93c97c52bc2f8c";
  }

  static const char* value(const ::mobileNet::GetDepth&) { return value(); }
};

template<>
struct DataType< ::mobileNet::GetDepth > {
  static const char* value()
  {
    return "mobileNet/GetDepth";
  }

  static const char* value(const ::mobileNet::GetDepth&) { return value(); }
};


// service_traits::MD5Sum< ::mobileNet::GetDepthRequest> should match
// service_traits::MD5Sum< ::mobileNet::GetDepth >
template<>
struct MD5Sum< ::mobileNet::GetDepthRequest>
{
  static const char* value()
  {
    return MD5Sum< ::mobileNet::GetDepth >::value();
  }
  static const char* value(const ::mobileNet::GetDepthRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::mobileNet::GetDepthRequest> should match
// service_traits::DataType< ::mobileNet::GetDepth >
template<>
struct DataType< ::mobileNet::GetDepthRequest>
{
  static const char* value()
  {
    return DataType< ::mobileNet::GetDepth >::value();
  }
  static const char* value(const ::mobileNet::GetDepthRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::mobileNet::GetDepthResponse> should match
// service_traits::MD5Sum< ::mobileNet::GetDepth >
template<>
struct MD5Sum< ::mobileNet::GetDepthResponse>
{
  static const char* value()
  {
    return MD5Sum< ::mobileNet::GetDepth >::value();
  }
  static const char* value(const ::mobileNet::GetDepthResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::mobileNet::GetDepthResponse> should match
// service_traits::DataType< ::mobileNet::GetDepth >
template<>
struct DataType< ::mobileNet::GetDepthResponse>
{
  static const char* value()
  {
    return DataType< ::mobileNet::GetDepth >::value();
  }
  static const char* value(const ::mobileNet::GetDepthResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MOBILENET_MESSAGE_GETDEPTH_H
