// Generated by gencpp from file mobileNet/GetDepthRequest.msg
// DO NOT EDIT!


#ifndef MOBILENET_MESSAGE_GETDEPTHREQUEST_H
#define MOBILENET_MESSAGE_GETDEPTHREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace mobileNet
{
template <class ContainerAllocator>
struct GetDepthRequest_
{
  typedef GetDepthRequest_<ContainerAllocator> Type;

  GetDepthRequest_()
    : x(0)
    , y(0)  {
    }
  GetDepthRequest_(const ContainerAllocator& _alloc)
    : x(0)
    , y(0)  {
  (void)_alloc;
    }



   typedef int16_t _x_type;
  _x_type x;

   typedef int16_t _y_type;
  _y_type y;





  typedef boost::shared_ptr< ::mobileNet::GetDepthRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::mobileNet::GetDepthRequest_<ContainerAllocator> const> ConstPtr;

}; // struct GetDepthRequest_

typedef ::mobileNet::GetDepthRequest_<std::allocator<void> > GetDepthRequest;

typedef boost::shared_ptr< ::mobileNet::GetDepthRequest > GetDepthRequestPtr;
typedef boost::shared_ptr< ::mobileNet::GetDepthRequest const> GetDepthRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::mobileNet::GetDepthRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::mobileNet::GetDepthRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::mobileNet::GetDepthRequest_<ContainerAllocator1> & lhs, const ::mobileNet::GetDepthRequest_<ContainerAllocator2> & rhs)
{
  return lhs.x == rhs.x &&
    lhs.y == rhs.y;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::mobileNet::GetDepthRequest_<ContainerAllocator1> & lhs, const ::mobileNet::GetDepthRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace mobileNet

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::mobileNet::GetDepthRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mobileNet::GetDepthRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mobileNet::GetDepthRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mobileNet::GetDepthRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mobileNet::GetDepthRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mobileNet::GetDepthRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::mobileNet::GetDepthRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "6d78a6b8c9650c754bf0432d3d1707c3";
  }

  static const char* value(const ::mobileNet::GetDepthRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x6d78a6b8c9650c75ULL;
  static const uint64_t static_value2 = 0x4bf0432d3d1707c3ULL;
};

template<class ContainerAllocator>
struct DataType< ::mobileNet::GetDepthRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "mobileNet/GetDepthRequest";
  }

  static const char* value(const ::mobileNet::GetDepthRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::mobileNet::GetDepthRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int16 x		#image x coordinate \n"
"int16 y		#image y coordinate\n"
;
  }

  static const char* value(const ::mobileNet::GetDepthRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::mobileNet::GetDepthRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.x);
      stream.next(m.y);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GetDepthRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::mobileNet::GetDepthRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::mobileNet::GetDepthRequest_<ContainerAllocator>& v)
  {
    s << indent << "x: ";
    Printer<int16_t>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<int16_t>::stream(s, indent + "  ", v.y);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MOBILENET_MESSAGE_GETDEPTHREQUEST_H
